[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/injector",
    "crates/runtime",
    "crates/ipc",
    "crates/package",
    "apps/manager/src-tauri",
]
default-members = [
    "crates/core",
    "crates/injector",
    "crates/runtime",
    "crates/ipc",
    "crates/package",
]

[workspace.package]
version = "0.1.1"
edition = "2021"
